/* 
	TEXT FOR LDC DISPLAYS
*/
# define  M_SETUP_TXT       	"SETUP"
# define  	M_CALIBRATE_TXT   	"CALIBRATE"
# define  	M_DIST_TXT        	"DISTURBERS"
# define  		DIST_EN_TXT	 	"ENABLE"
# define  		DIST_DIS_TXT	"DISABLE" 
# define  M_AFEGAIN_TXT     	"AFE GAIN"
# define  	AFE_GIN_TXT       	"INDOOR"
# define  	AFE_GOUT_TXT      	"OUTDOOR"
# define  M_NF_TXT          	"NOISE FLOOR"
# define  	M_NF_INDOORS_TXT  	"FOR INDOORS"
# define  		INNF28_TXT		"28 uVrms"
# define  		INNF45_TXT		"45 uVrms"
# define  		INNF62_TXT		"62 uVrms"
# define  		INNF78_TXT		"78 uVrms"
# define  		INNF95_TXT		"95 uVrms"
# define  		INNF112_TXT		"112 uVrms"
# define  		INNF130_TXT		"130 uVrms"
# define  		INNF146_TXT		"146 uVrms"
# define  	M_NF_OUTDOORS_TXT 	"FOR OUTOORS"	
# define  		OUTNF39_TXT		"390 uVrms"
# define  		OUTNF63_TXT		"630 uVrms"
# define  		OUTNF86_TXT		"860 uVrms"
# define  		OUTNF110_TXT	"1100 uVrms"
# define  		OUTNF114_TXT	"1140 uVrms"
# define  		OUTNF157_TXT	"1570 uVrms"
# define  		OUTNF180_TXT	"800 uVrms"
# define  		OUTNF200_TXT	"2000 uVrms"
# define  M_SPIK_REJ_TXT		"SPIKE REJECTION"
# define  	SPIKE0_TXT			"0"
# define  	SPIKE3_TXT			"3"
# define  	SPIKE6_TXT			"6"
# define  	SPIKE9_TXT			"9"
# define  	SPIKE12_TXT			"12"
# define  	SPIKE15_TXT			"15"
# define  M_WATCHDOG_THR		"WATCHDOR THR"
# define  M_MIN_STRIKE_TXT		"MINUMUM LIGHTNINGS"
# define  	MINL1_TXT			"1"
# define  	MINL5_TXT			"5"
# define  	MINL9_TXT			"9"
# define  	MINL16_TXT			"16"
# define  M_UNITS_TXT			"UNITS"
# define  	M_DISTANCE_TXT		"DISTANCE"
# define  		UNIT_KM_TXT 	"KM"
# define  		UNIT_MI_TXT		"MI"
# define  	M_LANG_TXT 			"LANGUAGE"
# define  		LANG_ENG_TXT	"ENG"
# define  		LANG_ESP_TXT	"ESP"
# define  M_RESET_TXT			"RESET REGISTERS"

# define  DATA_TXT				"DATA REGISTERS"
# define  	LIGHTC_TXT 			"LIGTHNING COUNT"
# define  	AVGDIST_TXT 		"DISTANCE AVERAGE"
# define  	NEAREST_TXT 		"CLOSEST"	
# define  RUNNING_TXT			"LISTENING"	
# define  OOF_TXT 				"OUT OF RANGE"
# define  RANGE_TXT 			"RANGE: %d %s"
# define  SOVER_TXT	        	"STORM OVER HEAD!!"
# define  EV_PERT_TXT	    	"DISTURBER DETECTED"
# define  EV_NOSIEHIGH_TXT  	"NOISE TO HIGH"
# define  EV_STRIKE_TXT			"STRIKE DETECTED!! "
 


/*
	MENU NAVIGATION
*/
# define MAIN_PG		0
# define SETUP_PG		1
# define DATA_PG		2
